### ISSUE TITLE
duplicates of art 

### ISSUE THREAD

**Issue by TiffanyCao** [jessechen1618/softdev_p01#5]
some art shows up twice or thrice or more, like Andiron

**Comment by jessechen1618** [comment]
Thanks. We're currently working on redesigning the home page; the andirons are just a temporary gallery. Unfortunately, some artists make pieces that look almost identical, but the andirons are not the same. They are physically different objects in the museum; the pictures may just look really similar (e.g. taken from the same angle under the same lighting). Maybe we could find a solution later. Thanks for bringing this up.

**Comment by erxclau** [comment]
We will check if artids are the same and or if the image url are the same. @StudentDX do you know how to make these required to be unique?

**Comment by StudentDX** [comment]
New cache is pre-selected.
